spring:
  application:
    name: ribbon-consumer2
server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   #注册中心的地址

provider:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8082,localhost:8083,localhost:8084
  ServerListRefreshInterval: 15000
